# Generated by Django 3.2.15 on 2023-01-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20230101_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='praesidiumyear',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='geslacht',
            field=models.CharField(blank=True, choices=[('MAN', 'Man'), ('ANDERS', 'Anders'), ('VROUW', 'Vrouw')], max_length=50),
        ),
    ]
