# Generated by Django 3.2.15 on 2023-02-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20230101_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praesidiummember',
            name='photo',
        ),
        migrations.AddField(
            model_name='praesidiumfunctionyearmember',
            name='photo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='geslacht',
            field=models.CharField(blank=True, choices=[('VROUW', 'Vrouw'), ('ANDERS', 'Anders'), ('MAN', 'Man')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=50),
        ),
    ]
