# Generated by Django 3.2.15 on 2023-12-26 22:36

import Backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_auto_20231226_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='link',
        ),
        migrations.AddField(
            model_name='picture',
            name='file',
            field=models.ImageField(null=True, upload_to='album', validators=[Backend.models.Picture.validate_image]),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='geslacht',
            field=models.CharField(blank=True, choices=[('MAN', 'Man'), ('VROUW', 'Vrouw'), ('ANDERS', 'Anders')], max_length=50),
        ),
    ]
